{"uuid": "c1ad6f4d-9add-44f1-9482-3f8f7683857c", "children": ["3ebce45d-a387-4f7d-8d2d-5b10a1995499"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: JavaScript code failed\nfrom unknown command: 'Runtime.evaluate' wasn't found\n  (Session info: chrome=133.0.6943.142)\nStacktrace:\n\tGetHandleVerifier [0x00007FF739E1C6A5+28789]\n\t(No symbol) [0x00007FF739D85B20]\n\t(No symbol) [0x00007FF739C18F9A]\n\t(No symbol) [0x00007FF739C05788]\n\t(No symbol) [0x00007FF739C03F2E]\n\t(No symbol) [0x00007FF739C0477F]\n\t(No symbol) [0x00007FF739C2F97B]\n\t(No symbol) [0x00007FF739C23200]\n\t(No symbol) [0x00007FF739C230A2]\n\t(No symbol) [0x00007FF739BF4A5E]\n\t(No symbol) [0x00007FF739BF29F3]\n\t(No symbol) [0x00007FF739CD7B31]\n\t(No symbol) [0x00007FF739C9732A]\n\t(No symbol) [0x00007FF739CBF7E3]\n\t(No symbol) [0x00007FF739C97103]\n\t(No symbol) [0x00007FF739C5FFC0]\n\t(No symbol) [0x00007FF739C61273]\n\tGetHandleVerifier [0x00007FF73A161AED+3458237]\n\tGetHandleVerifier [0x00007FF73A17829C+3550316]\n\tGetHandleVerifier [0x00007FF73A16DB9D+3507565]\n\tGetHandleVerifier [0x00007FF739EE2C6A+841274]\n\t(No symbol) [0x00007FF739D909EF]\n\t(No symbol) [0x00007FF739D8CB34]\n\t(No symbol) [0x00007FF739D8CCD6]\n\t(No symbol) [0x00007FF739D7C119]\n\tBaseThreadInitThunk [0x00007FFFDBDC259D+29]\n\tRtlUserThreadStart [0x00007FFFDDC4AF38+40]\n\n", "trace": "  File \"C:\\Users\\Dhivya\\PycharmProjects\\pythonProjectrevision\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Dhivya\\PycharmProjects\\pythonProjectrevision\\.venv1\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Dhivya\\PycharmProjects\\pythonProjectrevision\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dhivya\\PycharmProjects\\pythonProjectrevision\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dhivya\\PycharmProjects\\pythonProjectrevision\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dhivya\\py3xWebAutomationFramework\\tests\\vwoLoginTests\\test_vwo_login.py\", line 16, in setup\n    driver.maximize_window()\n  File \"C:\\Users\\Dhivya\\PycharmProjects\\pythonProjectrevision\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 622, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\Dhivya\\PycharmProjects\\pythonProjectrevision\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Dhivya\\PycharmProjects\\pythonProjectrevision\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1741682337420, "stop": 1741682339822}], "start": 1741682337420, "stop": 1741682340207}